import pygame

SCREEN_WIDTH = 600
SCREEN_HEIGHT = 650
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)

SCREEN_SURFACE = pygame.display.set_mode(SCREEN_SIZE)
CLOCK = pygame.time.Clock()

FPS = 60

CELL_PNG = "assets/cell"
PIECE_PNG = "assets/piece"
FOCUS_PNG = "assets/focus"

CELL_SIZE = 75
PIECE_SIZE = 75

CHESS_WIDTH = 600
CHESS_HEIGHT = 600
CHESS_SURFACE_SIZE = (CHESS_WIDTH, CHESS_HEIGHT)
CHESS_SURFACE_POSITION = (0, 50)

BG_COLOR = (55, 55, 55)
BORDER_COLOR = (0, 0, 0)
BORDER_WIDTH = 3
